INSERT INTO equipos (nombre, id_pais)
VALUES
("Ajax",7)
,("AZAlkmaar",7)
,("Breda",7)
,("Cambuur",7)
,("Den Haag",7)
,("FC Emmen",7)
,("Feyenoord",7)
,("G.A. Eagles",7)
,("Groningen",7)
,("Heerenveen",7)
,("Heracles",7)
,("Nijmegen",7)
,("PSV",7)
,("Sittard",7)
,("Sparta Rotterdam",7)
,("Twente",7)
,("Utrecht",7)
,("Venlo",7)
,("Vitesse",7)
,("Waalwijk",7)
,("Willem II",7)
,("Zwolle",7)
,("Angers",4)
,("Brest",4)
,("Clermont",4)
,("Estrasburgo",4)
,("Girondins",4)
,("Lens",4)
,("Lille",4)
,("Lorient",4)
,("Lyon",4)
,("MÃ³naco",4)
,("Marsella",4)
,("Metz",4)
,("Montpellier",4)
,("Nantes",4)
,("Niza",4)
,("PSG",4)
,("Reims",4)
,("Saint-Ã‰tienne",4)
,("Stade Rennais",4)
,("Troyes",4)
,("Arouca",8)
,("Belenenses",8)
,("Benfica",8)
,("Boavista",8)
,("Chaves",8)
,("Estoril",8)
,("Famalicao",8)
,("Gil Vicente",8)
,("MarÃ­timo",8)
,("Moreirense",8)
,("Oporto",8)
,("P. Ferreira",8)
,("Portimonense",8)
,("Rio Ave",8)
,("Santa Clara",8)
,("SC Braga",8)
,("Sporting CP",8)
,("Tondela",8)
,("V. Guimaraes",8)
,("Vizela",8)
,("Albacete",3)
,("AlcorcÃ³n",3)
,("AlmerÃ­a",3)
,("Amorebieta",3)
,("Burgos CF",3)
,("Cartagena",3)
,("CastellÃ³n",3)
,("Espanyol",3)
,("Fuenlabrada",3)
,("Girona",3)
,("Huesca",3)
,("Las Palmas",3)
,("LeganÃ©s",3)
,("LogroÃ±Ã©s",3)
,("Lugo",3)
,("MÃ¡laga",3)
,("Mallorca",3)
,("MirandÃ©s",3)
,("Ponferradina",3)
,("R. Sociedad B",3)
,("Rayo Vallecano",3)
,("Real Oviedo",3)
,("Real Valladolid",3)
,("Real Zaragoza",3)
,("Sabadell",3)
,("Sporting de GijÃ³n",3)
,("Tenerife",3)
,("UD Ibiza",3)
,("AC Milan",5)
,("Atalanta",5)
,("Benevento",5)
,("Bolonia",5)
,("Cagliari",5)
,("Crotone",5)
,("Empoli",5)
,("Fiorentina",5)
,("Genoa",5)
,("Inter",5)
,("Juventus",5)
,("Lazio",5)
,("NÃ¡poles",5)
,("Parma",5)
,("Roma",5)
,("Salernitana",5)
,("Sampdoria",5)
,("Sassuolo",5)
,("Spezia",5)
,("Torino",5)
,("Udinese",5)
,("Venezia",5)
,("Verona",5)
,("Barnsley",6)
,("Birmingham",6)
,("Blackburn",6)
,("Blackpool",6)
,("Bournemouth",6)
,("Bristol City",6)
,("Cardiff",6)
,("Coventry",6)
,("Derby",6)
,("Huddersfield",6)
,("Hull",6)
,("Luton",6)
,("Middlesbrough",6)
,("Millwall",6)
,("Nottingham Forest",6)
,("Peterborough",6)
,("Preston",6)
,("QPR",6)
,("Reading",6)
,("Rotherham",6)
,("Sheffield Wed",6)
,("Stoke",6)
,("Swansea",6)
,("Wycombe",6)
,("AlavÃ©s",3)
,("Athletic Club",3)
,("AtlÃ©tico de Madrid",3)
,("Barcelona",3)
,("CÃ¡diz",3)
,("Celta de Vigo",3)
,("Eibar",3)
,("Elche",3)
,("Getafe",3)
,("Granada",3)
,("Levante",3)
,("Osasuna",3)
,("Real Betis",3)
,("Real Madrid",3)
,("Real Sociedad",3)
,("Sevilla",3)
,("Valencia",3)
,("Villarreal",3)
,("AC Ajaccio",4)
,("Amiens",4)
,("Auxerre",4)
,("Bastia",4)
,("Chambly",4)
,("Chateauroux",4)
,("Dijon",4)
,("Dunkerque",4)
,("EA Guingamp",4)
,("Grenoble",4)
,("Le Havre",4)
,("Nancy",4)
,("Nimes",4)
,("Niort",4)
,("Paris FC",4)
,("Pau FC",4)
,("Quevilly Rouen",4)
,("Rodez",4)
,("SM Caen",4)
,("Sochaux",4)
,("Toulouse",4)
,("Valenciennes",4)
,("Arsenal",6)
,("Aston Villa",6)
,("Brentford",6)
,("Brighton",6)
,("Burnley",6)
,("Chelsea",6)
,("Crystal Palace",6)
,("Everton",6)
,("Fulham",6)
,("Leeds Utd",6)
,("Leicester",6)
,("Liverpool",6)
,("Manchester City",6)
,("Manchester Utd",6)
,("Newcastle",6)
,("Norwich",6)
,("Sheffield Utd",6)
,("Southampton",6)
,("Tottenham",6)
,("Watford",6)
,("West Brom",6)
,("West Ham",6)
,("Wolves",6)
