INSERT INTO equipos (nombre, id_pais)
VALUES
("Racing",3)
,("Andorra",3)
,("Villarreal B",3)
,("Wigan",6)
,("Sunderland",6)
,("Casa Pia",8)
,("Laval",4)
,("Annecy",4)
,("Lecce",5)
,("Cremonese",5)
,("Monza",5)
,("FC Volendam",7)
,("Excelsior",7)
